---
# tasks file for roles/containerd
#
#
#  维护者: vgacisco
#
#  version: v1.0
#  
#  8/10/22
#

- name: unarchive containerd
  unarchive:
    src: '{{item}}'
    dest: /
  with_fileglob:
    - "bin/cri-containerd-cni-*"

- name: mkdir /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: unarcd containers.tar
  unarchive:
    src: container.tar
    dest: /etc/containerd


- name: start containerd
  systemd:
    name: containerd
    state: started
    daemon_reload: yes
    enabled: yes

